http://ucidatascienceinitiative.github.io/IntroToJulia/Html/BasicProblems

# Starter Problems

## Strang Matrix Problem

In [54]:
function strang(n::Int)::Array{Float64,2}
    M = zeros(n, n)
    for i=1:n, j=1:n
        i == j && (M[i, j] = -2)
        abs(i - j) == 1 && (M[i, j] = 1)
    end
    M
end

strang(10)

10×10 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0

## Factorial Problem

In [61]:
function my_factorial(n::T)::T where T <: Integer
    @assert n >= zero(n)
    f = one(n)
    for i=2:n
        f *= i
    end
    f
end

for i=20:25
    f = my_factorial(i)
    println("[$(typeof(f))] $(lpad(i, 2))! = $f")
end

println()

for i=20:25
    f = my_factorial(big(i))
    println("[$(typeof(f))] $(lpad(i, 2))! = $f")
end

[Int64] 20! = 2432902008176640000
[Int64] 21! = -4249290049419214848
[Int64] 22! = -1250660718674968576
[Int64] 23! = 8128291617894825984
[Int64] 24! = -7835185981329244160
[Int64] 25! = 7034535277573963776

[BigInt] 20! = 2432902008176640000
[BigInt] 21! = 51090942171709440000
[BigInt] 22! = 1124000727777607680000
[BigInt] 23! = 25852016738884976640000
[BigInt] 24! = 620448401733239439360000
[BigInt] 25! = 15511210043330985984000000


## Binomial Problem

In [62]:
function binomial_rv(n, p)
    count = zero(n)
    for x=rand(n)
        x < p && (count+=1)
    end
    count
end

map(_ -> binomial_rv(10, .5), 1:10)

10-element Array{Int64,1}:
 4
 5
 8
 4
 7
 2
 5
 5
 7
 6

## Monte Carlo π Problem

In [134]:
function estimate_pi()::Float64
    n = 10_000_000
    inside_circle = 0
    for i=1:n
        x, y = 2rand(2) .- 1
        sqrt(x^2 + y^2) < 1 && (inside_circle += 1)
    end
    4inside_circle / n
end

println("π = $(estimate_pi())")
println(π)

π = 3.1418036
π = 3.1415926535897...


# Integration Problems

## Timeseries Generation Problem

In [135]:
using PyCall

In [138]:
function ar1(α, T)
    X = zeros(T + 1)
    for t=1:T
        X[t + 1] = α*X[t] + randn()
    end
    X
end

ar1(0.5, 200)

201-element Array{Float64,1}:
  0.0                
 -2.0127538472423896 
 -0.8518786641094896 
 -0.901276237809004  
  0.676200623983852  
  0.5059970467300796 
 -1.024420303532396  
 -0.2797248664672519 
 -1.0165107129024042 
  0.2738129712369164 
  0.39634491514473624
  0.7927589428299086 
 -1.511678373665991  
  ⋮                  
  1.7248218253523464 
  0.9324573351644346 
  1.1737301978715726 
  1.8918068414725635 
  0.9113322533733603 
  0.15424993863193748
  1.5630369784930782 
 -0.5167353983639883 
  0.534012312615646  
 -0.9501832507645185 
 -0.7232508786024713 
 -1.3341127089263838 